<?php
declare(strict_types=1);

// MixpanelIdentity SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

MixpanelIdentityUtility::setRegistrar(function (MixpanelIdentityUtility $u): void {
    $u->clean = [MixpanelIdentityClean::class, 'call'];
    $u->done = [MixpanelIdentityDone::class, 'call'];
    $u->make_error = [MixpanelIdentityMakeError::class, 'call'];
    $u->feature_add = [MixpanelIdentityFeatureAdd::class, 'call'];
    $u->feature_hook = [MixpanelIdentityFeatureHook::class, 'call'];
    $u->feature_init = [MixpanelIdentityFeatureInit::class, 'call'];
    $u->fetcher = [MixpanelIdentityFetcher::class, 'call'];
    $u->make_fetch_def = [MixpanelIdentityMakeFetchDef::class, 'call'];
    $u->make_context = [MixpanelIdentityMakeContext::class, 'call'];
    $u->make_options = [MixpanelIdentityMakeOptions::class, 'call'];
    $u->make_request = [MixpanelIdentityMakeRequest::class, 'call'];
    $u->make_response = [MixpanelIdentityMakeResponse::class, 'call'];
    $u->make_result = [MixpanelIdentityMakeResult::class, 'call'];
    $u->make_point = [MixpanelIdentityMakePoint::class, 'call'];
    $u->make_spec = [MixpanelIdentityMakeSpec::class, 'call'];
    $u->make_url = [MixpanelIdentityMakeUrl::class, 'call'];
    $u->param = [MixpanelIdentityParam::class, 'call'];
    $u->prepare_auth = [MixpanelIdentityPrepareAuth::class, 'call'];
    $u->prepare_body = [MixpanelIdentityPrepareBody::class, 'call'];
    $u->prepare_headers = [MixpanelIdentityPrepareHeaders::class, 'call'];
    $u->prepare_method = [MixpanelIdentityPrepareMethod::class, 'call'];
    $u->prepare_params = [MixpanelIdentityPrepareParams::class, 'call'];
    $u->prepare_path = [MixpanelIdentityPreparePath::class, 'call'];
    $u->prepare_query = [MixpanelIdentityPrepareQuery::class, 'call'];
    $u->graphql_body = [MixpanelIdentityGraphql::class, 'body'];
    $u->graphql_errors = [MixpanelIdentityGraphql::class, 'errors'];
    $u->result_basic = [MixpanelIdentityResultBasic::class, 'call'];
    $u->result_body = [MixpanelIdentityResultBody::class, 'call'];
    $u->result_headers = [MixpanelIdentityResultHeaders::class, 'call'];
    $u->transform_request = [MixpanelIdentityTransformRequest::class, 'call'];
    $u->transform_response = [MixpanelIdentityTransformResponse::class, 'call'];
});
